# Core Colors
background            #101510
foreground            #dfe4dc
selection_foreground  #101510
selection_background  #a1ced8
cursor                #a1ced8
cursor_text_color     #101510

# Regular Colors
color0  #262b26
color1  #ffb4ab
color2  #9ad4a2
color3  #bdeaf4
color4  #d3e8d2
color5  #a1ced8
color6  #d3e8d2
color7  #c1c9be

# Bright Colors
color9  #93000a
color10 #a1ced8
color11 #b5f1bc
color12 #bdeaf4
color13 #a1ced8
color14 #b7ccb7
color15 #363a35
